server:
  port: 8084

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: projet-service
            uri: http://localhost:8090
            predicates:
              - Path=/api/Projet/**
          - id: TacheService
            uri: http://localhost:8070
            predicates:
              - Path=/taches/**
          - id: ressource-service
            uri: http://localhost:8060
            predicates:
            - Path=/ressources/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/